linters-settings:
  funlen:
    lines: 150
    statements: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  goconst:
    ignore-tests: true
  gocyclo:
    min-complexity: 15
  importas:
    no-unaliased: true
    alias:
      # cover scrapligo packages
      - pkg: github.com/scrapli/scrapligo/(\w+)
        alias: scrapligo$1
  lll:
    line-length: 100
    tab-width: 4
  stylecheck:
    checks:
      - "-ST1000"

linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # https://github.com/golangci/golangci-lint/issues/2439#issuecomment-1002912465
  exclude-use-default: false
  exclude-dirs:
    - private
    - .private
  exclude-rules:
    # ignore package comments complaints in revive
    - linters:
        - revive
      text: "package-comments"

    # ignore some naming things for platforms
    - path: driver/platforms.go
      linters:
        - revive
      text: "exported"
    - path: driver/platforms.go
      linters:
        - revive
      text: "var-naming"

    # ignore some stuff for test packages
    - path: e2e/
      linters:
        - nestif
        - gocognit

  uniq-by-line: false

run:
  go: '1.24'

service:
  golangci-lint-version: 1.64.x
