---
version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - cyclop # already using gocyclo, and its good enough!
    - depguard
    - exhaustruct
    - paralleltest
    - perfsprint
    - varnamelen
    - wrapcheck
  settings:
    funlen:
      lines: 150
      statements: 50
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    importas:
      alias:
        - pkg: github.com/scrapli/scrapligo/(\w+)
          alias: scrapligo$1
      no-unaliased: true
    lll:
      line-length: 100
      tab-width: 4
    staticcheck:
      checks:
        - -ST1000
  exclusions:
    rules:
      - linters:
          - revive
        text: package-comments
      - linters:
          - gochecknoglobals
        path: constants/versions.go
      - linters:
          - revive
        path: cli/platforms.go
        text: exported
      - linters:
          - revive
        path: cli/platforms.go
        text: var-naming
      - linters:
          - revive
        path: netconf/types.go
        text: 'exported: exported const'
      - linters:
          - gocritic
        path: netconf/options
        text: singleCaseSwitch
      - linters:
          - gocognit
          - nestif
        path: e2e/
      - linters:
          - dupl
          - lll
        path: _test\.go
    paths:
      - private
      - .private
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
