---
name: cicd

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    env:
      SCRAPLIGO_DEBUG: debug
    uses: ./.github/workflows/lint.yaml

  test:
    env:
      SCRAPLIGO_DEBUG: debug
    uses: ./.github/workflows/test.yaml
